///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestProject.AustriaRecordingModules
{
    public partial class CreateProject_Austria
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void createNewProjectss(string MarketName, string iListIndex)
        {
			
        	sListIndex=iListIndex.ToString();
        	
			
			
			repo.FormMe.File.Click();
			
			repo.FormMe.New.Click();
			
			repo.FormMe.SearchMarket.Click();
			
			repo.FormMe.SearchMarket.PressKeys(MarketName);
			
			repo.FormMe.lst_Market.Click();
				
				
			
			repo.FormMe.btn_CreateNewProject.Click();
			
			repo.CreateNewProject.CreateNewProjectContainer.btn_OK.Click();
        }

    }
}
