///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Fireclass
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FireclassRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b2bee9a8-64d7-434d-b7f3-4f56d99560ae")]
    public partial class FireclassRepository : RepoGenBaseFolder
    {
        static FireclassRepository instance = new FireclassRepository();
        FireclassRepositoryFolders.FormMeAppFolder _formme;
        FireclassRepositoryFolders.CreateNewProjectAppFolder _createnewproject;

        /// <summary>
        /// Gets the singleton class instance representing the FireclassRepository element repository.
        /// </summary>
        [RepositoryFolder("b2bee9a8-64d7-434d-b7f3-4f56d99560ae")]
        public static FireclassRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FireclassRepository() 
            : base("FireclassRepository", "/", null, 0, false, "b2bee9a8-64d7-434d-b7f3-4f56d99560ae", ".\\RepositoryImages\\FireclassRepositoryb2bee9a8.rximgres")
        {
            _formme = new FireclassRepositoryFolders.FormMeAppFolder(this);
            _createnewproject = new FireclassRepositoryFolders.CreateNewProjectAppFolder(this);
        }

#region Variables

        string _sListIndex = "2";

        /// <summary>
        /// Gets or sets the value of variable sListIndex.
        /// </summary>
        [TestVariable("52ecb0f0-af2f-4d5e-bd04-1dafb7e347ce")]
        public string sListIndex
        {
            get { return _sListIndex; }
            set { _sListIndex = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b2bee9a8-64d7-434d-b7f3-4f56d99560ae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormMe folder.
        /// </summary>
        [RepositoryFolder("ed84a4da-623f-4bbf-92bb-8ba46ee2dc76")]
        public virtual FireclassRepositoryFolders.FormMeAppFolder FormMe
        {
            get { return _formme; }
        }

        /// <summary>
        /// The CreateNewProject folder.
        /// </summary>
        [RepositoryFolder("e07a3156-af95-4f3e-ac35-c1748ae9bc23")]
        public virtual FireclassRepositoryFolders.CreateNewProjectAppFolder CreateNewProject
        {
            get { return _createnewproject; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FireclassRepositoryFolders
    {
        /// <summary>
        /// The FormMeAppFolder folder.
        /// </summary>
        [RepositoryFolder("ed84a4da-623f-4bbf-92bb-8ba46ee2dc76")]
        public partial class FormMeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;
            RepoItemInfo _newInfo;
            RepoItemInfo _searchmarketInfo;
            RepoItemInfo _lst_marketInfo;
            RepoItemInfo _btn_createnewprojectInfo;

            /// <summary>
            /// Creates a new FormMe  folder.
            /// </summary>
            public FormMeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMe", "/form[@automationid='me']", parentFolder, 30000, null, true, "ed84a4da-623f-4bbf-92bb-8ba46ee2dc76", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "?/?/container[@automationid='PART_AutoHideControl']/?/?/button[@automationid='PART_ApplicationButton']/?/?/text[@text='File']", 90000, null, "d781f505-8a88-4245-82c1-c3201a92c693");
                _newInfo = new RepoItemInfo(this, "New", ".//text[@text='New']", 60000, null, "6d3ee0c8-d5ba-40ea-9764-e2367fa4d9a1");
                _searchmarketInfo = new RepoItemInfo(this, "SearchMarket", "progressbar//text/container[7]/text[@caption='']/text[@caption='']", 60000, null, "f892686f-16c1-410e-a76e-b57e2470f123");
                _lst_marketInfo = new RepoItemInfo(this, "lst_Market", ".//text[@caption='Recently Used Markets']/button[2]/list[@automationid='PART_Groups']/listitem[@index=$sListIndex]", 30000, null, "13cd759c-53df-4144-8f19-b1b4dedfecc5");
                _btn_createnewprojectInfo = new RepoItemInfo(this, "btn_CreateNewProject", "progressbar//button//text[@caption='Create new project...']", 60000, null, "becb4828-1b99-4df3-bdbf-84e7de7ed9c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed84a4da-623f-4bbf-92bb-8ba46ee2dc76")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed84a4da-623f-4bbf-92bb-8ba46ee2dc76")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("d781f505-8a88-4245-82c1-c3201a92c693")]
            public virtual Ranorex.Text File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("d781f505-8a88-4245-82c1-c3201a92c693")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The New item.
            /// </summary>
            [RepositoryItem("6d3ee0c8-d5ba-40ea-9764-e2367fa4d9a1")]
            public virtual Ranorex.Text New
            {
                get
                {
                    return _newInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The New item info.
            /// </summary>
            [RepositoryItemInfo("6d3ee0c8-d5ba-40ea-9764-e2367fa4d9a1")]
            public virtual RepoItemInfo NewInfo
            {
                get
                {
                    return _newInfo;
                }
            }

            /// <summary>
            /// The SearchMarket item.
            /// </summary>
            [RepositoryItem("f892686f-16c1-410e-a76e-b57e2470f123")]
            public virtual Ranorex.Text SearchMarket
            {
                get
                {
                    return _searchmarketInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SearchMarket item info.
            /// </summary>
            [RepositoryItemInfo("f892686f-16c1-410e-a76e-b57e2470f123")]
            public virtual RepoItemInfo SearchMarketInfo
            {
                get
                {
                    return _searchmarketInfo;
                }
            }

            /// <summary>
            /// The lst_Market item.
            /// </summary>
            [RepositoryItem("13cd759c-53df-4144-8f19-b1b4dedfecc5")]
            public virtual Ranorex.ListItem lst_Market
            {
                get
                {
                    return _lst_marketInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The lst_Market item info.
            /// </summary>
            [RepositoryItemInfo("13cd759c-53df-4144-8f19-b1b4dedfecc5")]
            public virtual RepoItemInfo lst_MarketInfo
            {
                get
                {
                    return _lst_marketInfo;
                }
            }

            /// <summary>
            /// The btn_CreateNewProject item.
            /// </summary>
            [RepositoryItem("becb4828-1b99-4df3-bdbf-84e7de7ed9c4")]
            public virtual Ranorex.Text btn_CreateNewProject
            {
                get
                {
                    return _btn_createnewprojectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btn_CreateNewProject item info.
            /// </summary>
            [RepositoryItemInfo("becb4828-1b99-4df3-bdbf-84e7de7ed9c4")]
            public virtual RepoItemInfo btn_CreateNewProjectInfo
            {
                get
                {
                    return _btn_createnewprojectInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewProjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("e07a3156-af95-4f3e-ac35-c1748ae9bc23")]
        public partial class CreateNewProjectAppFolder : RepoGenBaseFolder
        {
            FireclassRepositoryFolders.CreateNewProjectContainerFolder _createnewprojectcontainer;

            /// <summary>
            /// Creates a new CreateNewProject  folder.
            /// </summary>
            public CreateNewProjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewProject", "/form[@title='Create New Project']", parentFolder, 30000, null, true, "e07a3156-af95-4f3e-ac35-c1748ae9bc23", "")
            {
                _createnewprojectcontainer = new FireclassRepositoryFolders.CreateNewProjectContainerFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e07a3156-af95-4f3e-ac35-c1748ae9bc23")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e07a3156-af95-4f3e-ac35-c1748ae9bc23")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNewProjectContainer folder.
            /// </summary>
            [RepositoryFolder("5e72c4f0-65b6-4c68-856c-46296adc932c")]
            public virtual FireclassRepositoryFolders.CreateNewProjectContainerFolder CreateNewProjectContainer
            {
                get { return _createnewprojectcontainer; }
            }
        }

        /// <summary>
        /// The CreateNewProjectContainerFolder folder.
        /// </summary>
        [RepositoryFolder("5e72c4f0-65b6-4c68-856c-46296adc932c")]
        public partial class CreateNewProjectContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_okInfo;

            /// <summary>
            /// Creates a new CreateNewProjectContainer  folder.
            /// </summary>
            public CreateNewProjectContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewProjectContainer", "container[1]", parentFolder, 30000, null, false, "5e72c4f0-65b6-4c68-856c-46296adc932c", "")
            {
                _btn_okInfo = new RepoItemInfo(this, "btn_OK", ".//button[@text='OK']", 30000, null, "7be3706a-c77b-4d38-8abc-73e95fd77029");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e72c4f0-65b6-4c68-856c-46296adc932c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e72c4f0-65b6-4c68-856c-46296adc932c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btn_OK item.
            /// </summary>
            [RepositoryItem("7be3706a-c77b-4d38-8abc-73e95fd77029")]
            public virtual Ranorex.Button btn_OK
            {
                get
                {
                    return _btn_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btn_OK item info.
            /// </summary>
            [RepositoryItemInfo("7be3706a-c77b-4d38-8abc-73e95fd77029")]
            public virtual RepoItemInfo btn_OKInfo
            {
                get
                {
                    return _btn_okInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
