///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestProject.Recording_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane recording.
    /// </summary>
    [TestModule("50b02cdd-3f07-45d7-8b50-359e1f9bb80b", ModuleType.Recording, 1)]
    public partial class Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestProject.NGConsysRepository repository.
        /// </summary>
        public static global::TestProject.NGConsysRepository repo = global::TestProject.NGConsysRepository.Instance;

        static Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane instance = new Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Libraries.SlotCards_Functions.VerifySlotCardsAndBackplanesDistributionWithOnePanel("TC_51410_Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane", "Add Devices");
            Delay.Milliseconds(0);
            
            Libraries.Panel_Functions.DeletePanel(ValueConverter.ArgumentFromString<int>("NumberofPanels", "1"), "PanelNode", ValueConverter.ArgumentFromString<int>("rowNumber", "1"));
            Delay.Milliseconds(0);
            
            Libraries.SlotCards_Functions.VerifySlotCardsAndBackplanesDistributionWithOnePanel("TC_51410_Verify_PCH800_PCS800_POS800_PNI800_FBI800_Slot_Allocation_In_Backplane", "Add Devices_And_Reopen_Project");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.SaveProject("51410");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.Application_Close(ValueConverter.ArgumentFromString<bool>("Save", "False"), ValueConverter.ArgumentFromString<bool>("SaveConfirmation", "False"), "");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
