///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestProject.Recording_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds recording.
    /// </summary>
    [TestModule("3ac8ba58-8356-437c-8589-5e08fa919379", ModuleType.Recording, 1)]
    public partial class Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestProject.NGConsysRepository repository.
        /// </summary>
        public static global::TestProject.NGConsysRepository repo = global::TestProject.NGConsysRepository.Instance;

        static Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds instance = new Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_Pasting_Of_Points_In_Loop_Where_Points_Limit_Exceeds Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Libraries.Panel_Functions.AddPanels(ValueConverter.ArgumentFromString<int>("NumberofPanels", "1"), "Pro32xD", "");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("Node");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Node");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromMainProcessorGallery("PLX800", "Loops", "PFI");
            Delay.Milliseconds(0);
            
            Libraries.InventoryGrid_Functions.verifyInventoryGridProperties("7", "Label", "PLX800-E");
            Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.ClickOnNavigationTreeExpander("Backplane");
            //Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("PLX");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("PLX800-E");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromMultiplePointWizardWithRegion("801 CH", ValueConverter.ArgumentFromString<int>("DeviceQty", "50"), "4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 45s.", new RecordItemIndex(9));
            Delay.Duration(45000, false);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Node");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.RightClickOnSelectedInventoryGridRow("7");
            Delay.Milliseconds(0);
            
            // Copy
            Libraries.Devices_Functions.clickContextMenuOptionOnRightClick("3");
            Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.ClickOnNavigationTreeExpander("PFI");
            //Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Built-in Loop-A");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("801 CH", "Detectors");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.RightClickOnSelectedInventoryGridRow("1");
            Delay.Milliseconds(0);
            
            //Libraries.Devices_Functions.verifyContextMenuOptionOnRightClickEnabledOrDisabled("Paste");
            //Delay.Milliseconds(0);
            
            // Paste
            Libraries.Devices_Functions.clickContextMenuOptionOnRightClick("1");
            Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.clickOnPasteButton();
            //Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.clickOnPasteButton();
            //Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.MoveScrollBarDownInPointsGrid();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='801 CH - 125') on item 'FormMe.LastPointGridLabel'.", repo.FormMe.LastPointGridLabelInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.FormMe.LastPointGridLabelInfo, "Text", "801 CH - 125");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Node");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.RightClickOnSelectedInventoryGridRow("7");
            Delay.Milliseconds(0);
            
            // Cut
            Libraries.Devices_Functions.clickContextMenuOptionOnRightClick("2");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Built-in Loop-B");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("801 CH", "Detectors");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.RightClickOnSelectedInventoryGridRow("1");
            Delay.Milliseconds(0);
            
            //Libraries.Devices_Functions.verifyContextMenuOptionOnRightClickEnabledOrDisabled("Paste");
            //Delay.Milliseconds(0);
            
            // Paste
            Libraries.Devices_Functions.clickContextMenuOptionOnRightClick("1");
            Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.clickOnPasteButton();
            //Delay.Milliseconds(0);
            
            //Libraries.Common_Functions.clickOnPasteButton();
            //Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.MoveScrollBarDownInPointsGrid();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='801 CH - 250') on item 'FormMe.LastPointGridLabel'.", repo.FormMe.LastPointGridLabelInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.FormMe.LastPointGridLabelInfo, "Text", "801 CH - 250");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
