///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestProject.Recording_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value recording.
    /// </summary>
    [TestModule("f438bcb8-c6c3-4ea3-8fcf-a1c0f1277e62", ModuleType.Recording, 1)]
    public partial class Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestProject.NGConsysRepository repository.
        /// </summary>
        public static global::TestProject.NGConsysRepository repo = global::TestProject.NGConsysRepository.Instance;

        static Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value instance = new Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Libraries.Panel_Functions.AddPanels(ValueConverter.ArgumentFromString<int>("NumberofPanels", "1"), "Pro32xD", "");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("Node");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("PFI");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Built-in Loop-A");
            Delay.Milliseconds(0);
            
            Libraries.IS_Functions.VerifyEnableDisableISDevicesOnChangingCableCapacitance("TC_205_Verify_If_We_Can_Add_More_IS_Devices_To_EXI800_When_We_Decrease_Increase_The_Cable_Capacitance_Value", "Add EXI Devices", "Add IS Devices");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
