///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestProject.Recording_Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC recording.
    /// </summary>
    [TestModule("9544df86-5f59-4978-8aac-1422cd7cfdf5", ModuleType.Recording, 1)]
    public partial class Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::TestProject.NGConsysRepository repository.
        /// </summary>
        public static global::TestProject.NGConsysRepository repo = global::TestProject.NGConsysRepository.Instance;

        static Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC instance = new Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_Isolator_Units_Calculation_On_Changing_Base_Of_Non_Isolator_Device_To_Isolator_Base_FC Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Libraries.Panel_Functions.AddPanelsFC(ValueConverter.ArgumentFromString<int>("NumberofPanels", "1"), "FIRECLASS 64-2", "");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("Node");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeExpander("FIM");
            Delay.Milliseconds(0);
            
            Libraries.Common_Functions.ClickOnNavigationTreeItem("Built-in Loop-A");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("400CH", "Detectors");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("460H", "Call Points");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AssignDeviceBase("460H - 2", "4BI 4\" [517.050.043]", "13");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("410RIM", "Ancillary");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("445SR", "Detectors");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("410SNM", "Ancillary");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("460P", "Ancillary");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AssignDeviceBase("460P - 6", "4BI 4\" [517.050.043]", "13");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("410CIM", "Ancillary");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AddDevicesfromGallery("400P", "Ancillary");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.AssignDeviceBaseIfBlank("400P - 8", "4BI 4\" [517.050.043]", "13");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.DragAndDropDevicesInPhysicalLayout("A:5", "A:4");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.DragAndDropDevicesInPhysicalLayout("A:6", "A:4");
            Delay.Milliseconds(0);
            
            //Libraries.Devices_Functions.DragAndDropDevicesInPhysicalLayout("22", "11");
            //Delay.Milliseconds(0);
            
            //Libraries.Devices_Functions.DragAndDropDevicesInPhysicalLayout("29", "15");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProfileConsys1.tab_Points' at Center.", repo.ProfileConsys1.tab_PointsInfo, new RecordItemIndex(19));
            repo.ProfileConsys1.tab_Points.Click();
            Delay.Milliseconds(200);
            
            //Libraries.IS_Functions.VerifyIsolatorUnits("3.5", "FIM");
            //Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("7", "1");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("8", "5");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("9", "5");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("10", "1");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("11", "0");
            Delay.Milliseconds(0);
            
            Libraries.Devices_Functions.VerifyValueOfParameterInPhysicalLayout("12", "0");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
